
# Available options for joystick / trigger :
# 0: Left/Right Axis stick left
# 1: Up/Down Axis stick left
# 2: LT
# 3: Left/Right Axis stick right
# 4: Up/Down Axis stick right
# 5: RT
# 6: cross key left/right
# 7: cross key up/down

# Set stick or trigger responsible for forward / backward movement
axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular: 3  # Right thumb stick horizontal
scale_angular: 0.4

# Avalable options for buttons:
# 0: A
# 1: B
# 2: X
# 3: Y
# 4: LB
# 5: RB
# 6: back
# 7: start
# 8: power
# 9: Button stick left
# 10: Button stick right

# Set dead man switch
enable_button: 2  # Left trigger button

# Set turbo button
enable_turbo_button: 5  # Right trigger button

